sudo: required

services:
  - docker

before_install:
  - docker build -t vinn2580/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vinn2580/react-test npm test -- --coverage

after_success:
  - docker build -t vinn2580/multi-client ./client
  - docker build -t vinn2580/multi-nginx ./nginx
  - docker build -t vinn2580/multi-server ./server
  - docker build -t vinn2580/multi-worker ./worker

  #Login into docker CLI

  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub

  - docker push vinn2580/multi-client 
  - docker push vinn2580/multi-nginx
  - docker push vinn2580/multi-server
  - docker push vinn2580/multi-worker
  #//end